name: mi primer GITHub action
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: saludar
      run: echo Hello hace un push
    - name: docker
      run: docker -v 
    - name: build Image
      run: docker build . -t serafodevops/gitactnodeimage:240520
    - name: list image
      run: docker images
    - name: pusing to docker hub
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo 'Docker login'
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        echo 'Sending to hib'
        docker push serafodevops/gitactnodeimage:240520
       
    
    
