name: mi primer GITHub action
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: saludar
      run: echo Hello hace un push
    - name: docker
      run: docker -v 
    - name: build Image
      run: docker build . -t serafodevops/gitactnodeimage:240520
    - name: list image
      run: docker images
    - name: running image
      run: docker run  -d serafodevops/gitactnodeimage:240520
    - name: listing containers
      run: docker ps -a
      
    
